### ISSUE TITLE
Implement CEM naming convention

### ISSUE THREAD

**Issue by astrotim** [BastienZag/generator-da#17]
Currently, if I create a component called "ui-block", it generates the class name as:

`prefix-uiBlock`

Can this please be:

`prefix-ui-block`

**Comment by BastienZag** [comment]
Example:
I just created a component for rcc. the component is the email consent form.

my component class is: rcc-emailConsentForm

and I have inside:
rcc-emailConsentForm-title
rcc-emailConsentForm-submit
etc... 

there is no - between emailConsentForm because it's the component name and I think that will be very hard to know what's the component if everything is dashed like:
rcc-email-consent-form-title

I think the better way is: 
rcc-emailConsentForm-title
preffix-componentName-elements

I'm adding this issue as an investigation task and we can talk about it during the next review.
